package uci.atcnea.student.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONFIG".
 */
public class Config {

    private Long id;
    private String macDevices;

    public Config() {
    }

    public Config(Long id) {
        this.id = id;
    }

    public Config(Long id, String macDevices) {
        this.id = id;
        this.macDevices = macDevices;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMacDevices() {
        return macDevices;
    }

    public void setMacDevices(String macDevices) {
        this.macDevices = macDevices;
    }

}
