package uci.atcnea.student.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import uci.atcnea.student.dao.User;
import uci.atcnea.student.dao.Lesson;
import uci.atcnea.student.dao.Nomenclator;
import uci.atcnea.student.dao.Resource;
import uci.atcnea.student.dao.FileRecord;
import uci.atcnea.student.dao.UserLesson;
import uci.atcnea.student.dao.Group;
import uci.atcnea.student.dao.Message;
import uci.atcnea.student.dao.Task;
import uci.atcnea.student.dao.TaskRecord;
import uci.atcnea.student.dao.Config;

import uci.atcnea.student.dao.UserDao;
import uci.atcnea.student.dao.LessonDao;
import uci.atcnea.student.dao.NomenclatorDao;
import uci.atcnea.student.dao.ResourceDao;
import uci.atcnea.student.dao.FileRecordDao;
import uci.atcnea.student.dao.UserLessonDao;
import uci.atcnea.student.dao.GroupDao;
import uci.atcnea.student.dao.MessageDao;
import uci.atcnea.student.dao.TaskDao;
import uci.atcnea.student.dao.TaskRecordDao;
import uci.atcnea.student.dao.ConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig nomenclatorDaoConfig;
    private final DaoConfig resourceDaoConfig;
    private final DaoConfig fileRecordDaoConfig;
    private final DaoConfig userLessonDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig taskRecordDaoConfig;
    private final DaoConfig configDaoConfig;

    private final UserDao userDao;
    private final LessonDao lessonDao;
    private final NomenclatorDao nomenclatorDao;
    private final ResourceDao resourceDao;
    private final FileRecordDao fileRecordDao;
    private final UserLessonDao userLessonDao;
    private final GroupDao groupDao;
    private final MessageDao messageDao;
    private final TaskDao taskDao;
    private final TaskRecordDao taskRecordDao;
    private final ConfigDao configDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        nomenclatorDaoConfig = daoConfigMap.get(NomenclatorDao.class).clone();
        nomenclatorDaoConfig.initIdentityScope(type);

        resourceDaoConfig = daoConfigMap.get(ResourceDao.class).clone();
        resourceDaoConfig.initIdentityScope(type);

        fileRecordDaoConfig = daoConfigMap.get(FileRecordDao.class).clone();
        fileRecordDaoConfig.initIdentityScope(type);

        userLessonDaoConfig = daoConfigMap.get(UserLessonDao.class).clone();
        userLessonDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        taskRecordDaoConfig = daoConfigMap.get(TaskRecordDao.class).clone();
        taskRecordDaoConfig.initIdentityScope(type);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        nomenclatorDao = new NomenclatorDao(nomenclatorDaoConfig, this);
        resourceDao = new ResourceDao(resourceDaoConfig, this);
        fileRecordDao = new FileRecordDao(fileRecordDaoConfig, this);
        userLessonDao = new UserLessonDao(userLessonDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        taskRecordDao = new TaskRecordDao(taskRecordDaoConfig, this);
        configDao = new ConfigDao(configDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(Nomenclator.class, nomenclatorDao);
        registerDao(Resource.class, resourceDao);
        registerDao(FileRecord.class, fileRecordDao);
        registerDao(UserLesson.class, userLessonDao);
        registerDao(Group.class, groupDao);
        registerDao(Message.class, messageDao);
        registerDao(Task.class, taskDao);
        registerDao(TaskRecord.class, taskRecordDao);
        registerDao(Config.class, configDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        lessonDaoConfig.getIdentityScope().clear();
        nomenclatorDaoConfig.getIdentityScope().clear();
        resourceDaoConfig.getIdentityScope().clear();
        fileRecordDaoConfig.getIdentityScope().clear();
        userLessonDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        taskRecordDaoConfig.getIdentityScope().clear();
        configDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public NomenclatorDao getNomenclatorDao() {
        return nomenclatorDao;
    }

    public ResourceDao getResourceDao() {
        return resourceDao;
    }

    public FileRecordDao getFileRecordDao() {
        return fileRecordDao;
    }

    public UserLessonDao getUserLessonDao() {
        return userLessonDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TaskRecordDao getTaskRecordDao() {
        return taskRecordDao;
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

}
