package uci.atcnea.student.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import uci.atcnea.student.dao.FileRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE_RECORD".
*/
public class FileRecordDao extends AbstractDao<FileRecord, Long> {

    public static final String TABLENAME = "FILE_RECORD";

    /**
     * Properties of entity FileRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CreatedAt = new Property(1, String.class, "createdAt", false, "CREATED_AT");
        public final static Property TransferId = new Property(2, Long.class, "transferId", false, "TRANSFER_ID");
        public final static Property UserId = new Property(3, long.class, "userId", false, "USER_ID");
        public final static Property ResourceId = new Property(4, long.class, "resourceId", false, "RESOURCE_ID");
    };

    private DaoSession daoSession;

    private Query<FileRecord> user_FilerecordQuery;
    private Query<FileRecord> resource_FilerecordQuery;

    public FileRecordDao(DaoConfig config) {
        super(config);
    }
    
    public FileRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CREATED_AT\" TEXT," + // 1: createdAt
                "\"TRANSFER_ID\" INTEGER," + // 2: transferId
                "\"USER_ID\" INTEGER NOT NULL ," + // 3: userId
                "\"RESOURCE_ID\" INTEGER NOT NULL );"); // 4: resourceId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE_RECORD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FileRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(2, createdAt);
        }
 
        Long transferId = entity.getTransferId();
        if (transferId != null) {
            stmt.bindLong(3, transferId);
        }
        stmt.bindLong(4, entity.getUserId());
        stmt.bindLong(5, entity.getResourceId());
    }

    @Override
    protected void attachEntity(FileRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FileRecord readEntity(Cursor cursor, int offset) {
        FileRecord entity = new FileRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // createdAt
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // transferId
            cursor.getLong(offset + 3), // userId
            cursor.getLong(offset + 4) // resourceId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FileRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreatedAt(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTransferId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setUserId(cursor.getLong(offset + 3));
        entity.setResourceId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FileRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FileRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "filerecord" to-many relationship of User. */
    public List<FileRecord> _queryUser_Filerecord(long userId) {
        synchronized (this) {
            if (user_FilerecordQuery == null) {
                QueryBuilder<FileRecord> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_FilerecordQuery = queryBuilder.build();
            }
        }
        Query<FileRecord> query = user_FilerecordQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

    /** Internal query to resolve the "filerecord" to-many relationship of Resource. */
    public List<FileRecord> _queryResource_Filerecord(long resourceId) {
        synchronized (this) {
            if (resource_FilerecordQuery == null) {
                QueryBuilder<FileRecord> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ResourceId.eq(null));
                resource_FilerecordQuery = queryBuilder.build();
            }
        }
        Query<FileRecord> query = resource_FilerecordQuery.forCurrentThread();
        query.setParameter(0, resourceId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getResourceDao().getAllColumns());
            builder.append(" FROM FILE_RECORD T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN RESOURCE T1 ON T.\"RESOURCE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FileRecord loadCurrentDeep(Cursor cursor, boolean lock) {
        FileRecord entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }
        offset += daoSession.getUserDao().getAllColumns().length;

        Resource resource = loadCurrentOther(daoSession.getResourceDao(), cursor, offset);
         if(resource != null) {
            entity.setResource(resource);
        }

        return entity;    
    }

    public FileRecord loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FileRecord> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FileRecord> list = new ArrayList<FileRecord>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FileRecord> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FileRecord> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
